### ISSUE TITLE
js example as default in readme

### ISSUE THREAD

**Issue by wickkidd** [politico/vue-accessible-selects#62]
If popularity of this library is desired, I would use javascript (latest release is probably fine) for the initial/first/default example of usage (and correspondingly forego unnecessary complications like `export default Vue.extend({})`). I would also include all possible implementation approaches (e.g. I just had to look up props for `SelectMulti` because I was not able to use `v-model` and luckily saw that [`values` is a prop](https://github.com/politico/vue-accessible-selects/blob/main/src/SelectMulti.vue#L101)). If you want to additionally show one in typescript then I would call it out as a ts example.

Further, I would reduce the indents to 2 spaces in the examples.

**Comment by jackkoppa** [comment]
Excellent points all around. We definitely need a way that's a quicker onboarding process, whether we do that through a [Storybook docs page](https://storybook.js.org/docs/react/writing-docs/docs-page), or a standalone VuePress thing or something. And the points are super well-taken re: formatting of examples.

**Comment by jackkoppa** [comment]
Hi @RED143 - I'd like us to do a couple things for this issue:

1. Let's switch the examples in the README to be as simple as possible - so that would be showing a JS, rather than TS, component - likely no method handlers needed, just `v-model`. And probably having nothing about custom SCSS, just show importing the mixins & initializing them w/ no args

2. Then, let's get to work on improving our onboarding site, so that if someone opens 
a) I'd like an intro page to load first, and it can be super similar to this one that another library put together using Storybook MDX: https://reaviz.io/?path=/story/docs-intro--page (code is here: https://github.com/reaviz/reaviz/blob/master/docs/getting-started/Intro.story.mdx)
b) and then in addition to our `SelectSingle.stories` and `SelectMulti.stories`, which can stay exactly the way they are & be the source of truth for "here's all the things they *can* do", we can probably create something like
`CommonUseCases.stories.mdx` and `StylingOptions.stories.mdx` - these can be done in a follow-up ticket, but I want us to be thinking about how we'd document, more simply "here's a few common things you might need to do w/ `SelectMulti` and "here's how you pass in custom styling variables"

So for this particular issue, let's just worry about `1` and `2a`, then we can discuss & work on `2b` some other time

**Comment by jackkoppa** [comment]
Awesome work by @RED143 on this, in #69!

Closing ✅
